// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRYYgykoHL7lkULnkx3J4sxrQuhAfyYtQ',
    appId: '1:600509092671:android:d26455cc35dca84ddff98a',
    messagingSenderId: '600509092671',
    projectId: 'my-new-social-chat-app',
    storageBucket: 'my-new-social-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx19lhh-2jrejfCX1pfslgOD-3btP4G34',
    appId: '1:600509092671:ios:8d15a0e337cc467bdff98a',
    messagingSenderId: '600509092671',
    projectId: 'my-new-social-chat-app',
    storageBucket: 'my-new-social-chat-app.appspot.com',
    androidClientId: '600509092671-rh67q0akn0kffrvj5bcjo2urg5qrtbfe.apps.googleusercontent.com',
    iosClientId: '600509092671-3dfbg4m0vpnuk5ratc79c63bnqnav5n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.socioChat',
  );
}
